# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2fc8ce7e2a6f9ebb8e89298fc674cf3c86230e3ba15638eea5be9d524f357a6358273668e1eb1b17bff3002b9d74bde5de266bc5988552f37f555cf6ae9be8c7

test:
  secret_key_base: 242510b6b2bc13582e603aaf370fd249512dc94d1da4d3a6274a9314257fe2f2cba6b6e22d450a7e6431244441cb07bc976e66fd76281bd22663ea81eb94b841

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
